export const bars = [
  { index: 0, scaleY: .4 },
  { index: 1, scaleY: .3 },
  { index: 2, scaleY: .2 },
  { index: 3, scaleY: .1 },
  { index: 4, scaleY: .5 },
  { index: 5, scaleY: .6 },
  { index: 6, scaleY: .5 },
  { index: 7, scaleY: .4 },
  { index: 8, scaleY: .3 },
  { index: 9, scaleY: .2 },
  { index: 10, scaleY: .1 },
  { index: 11, scaleY: .6 },
  { index: 12, scaleY: 1 },
  { index: 13, scaleY: .5 },
  { index: 14, scaleY: .4 },
  { index: 15, scaleY: .3 },
  { index: 16, scaleY: .5 },
  { index: 17, scaleY: .4 },
  { index: 18, scaleY: .3 },
  { index: 19, scaleY: .2 },
  { index: 20, scaleY: .1 },
  { index: 21, scaleY: .6 },
  { index: 22, scaleY: .5 },
  { index: 23, scaleY: .4 },
]